theme = "hugo-uno"
languageCode = "en-us"
contentdir = "content"
publishdir = "public"
builddrafts = false
# baseurl = "localhost"
baseurl = "http://bedlamha.us/"
canonifyurls = true
title = "Bedlam House"
author = "Bedlam House Media"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."


[taxonomies]
   category = "categories"
   tag = "tags"
[Params]
  AuthorName = "Bedlam House"
  description = "A digital collection of content, criticism, and takes."
  cover = "/images/cover.jpg"
  logo = "/images/logo.png"